### ISSUE TITLE
Question about seasonal keys in quotes.json

### ISSUE THREAD

**Issue by nizhf** [KC3Kai/kc3-translations#824]
Hi, I have a question about how seasonal keys work in quotes.json. 

For example, now is Setsubun season. If a ship has "2@Setsubun" and "2@Setsubun2024", which quote will be loaded?
And if a ship only has "2@Setsubun2016", will this be loaded?
Should I better add the year number or not?

Another question is: How does the program decide which quotes are for the current season? As an example, in the season of Saury, [kcwiki.cn](https://zh.kcwiki.cn/wiki/%E5%AD%A3%E8%8A%82%E6%80%A7/2023%E5%B9%B4%E7%A7%8B%E5%88%80%E9%B1%BC%E7%A5%AD%E5%85%B8) shows many ships also have special voices for Fall or LateFall.

**Comment by sinsinpub** [comment]
it's a bit complex. tldr:
 * kancolle game voice lines are identified by a numeric ID (which is the part before the `@` mark), and kc3 defines a descriptive key for easier reading (eg, the `Setsubun` part after `@` mark).
 * when voice audio files are loaded by the game, kc3 observes the size (in bytes) of the .mp3 file (in http response headers), then chooses a proper seasonal key according the size, joined with the voice number, looks up in our quotes json data. if a quote line matched, it will be displayed.
 * sometimes, multiple .mp3 files for the same voice number are exactly the same size, kc3 has another data map to indicate their seasonal keys according their effective seasons (by months of year)

the details of logics can be found in [`Meta.ja` file](https://github.com/KC3Kai/KC3Kai/blob/develop/src/library/modules/Meta.js#L1250), and the map data of file sizes and seasonal keys can be found in [`quotes_size.json` file](https://github.com/KC3Kai/KC3Kai/blob/develop/src/data/quotes_size.json). here [`fud_weekly.json`](https://github.com/KC3Kai/KC3Kai/blob/develop/src/data/fud_weekly.json#L200) is the map data of same size seasonal keys and effective months 

these data are all kept updating by @fourinone with en quotes, so generally we wait for him to scan all the new quotes, and see what seasonal keys are defined and used in `en/quotes.json`, since the key names have to be defined and matched with `quotes_size.json` (sometimes in `fud_weekly.json` too).
but recently, due to the translator for en.kancollewiki.net has retired, we are also lack sources of en translated quotes.

**Comment by nizhf** [comment]
Thank you for your explanation!
The old Kantour tool for SCN quotes has not been maintained for many years. I am trying to write a new Python script to get SCN seasonal quotes from kcwiki.cn (semi-)automatically. The procedure, I would imagine, is to first parse new quotes from the [kcwikizh seasonal page](https://zh.kcwiki.cn/wiki/%E5%AD%A3%E8%8A%82%E6%80%A7), map their voice type ID to the ID used in KC3 (`Sec1` --> `2` or `Poke(1)`, ...), then find the corresponding season key in `quotes_size.json`. Still, the keys need to be revised by humans before being merged into the regular quotes. 
I tried my small demo on Setsubun quotes, and it seems to work. I will try it for more seasons.

Also, do you plan to update tools/remodelGroups.json?

**Comment by sinsinpub** [comment]
yea, of course if it's needed, updated now.
it can be simply get by executing this in kc3 strategy room devtools console, when the game has updated remodels.
```js
copy(JSON.stringify(RemodelDb._db.remodelGroups))
```
